### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cristiano939** [andrebnassis/BlipSDKHelperLibrary#1]
I'll not complain about anything, just suggestions to make this project more awesome :D

1: The title  "4. Sending Weblink(Image with link)"
The **weblink** is not an Image with link, it's the opposite, a Link with image. 

2: 
There are two kind of Facebook lists, with the first entry as a cover, 
(https://scontent.fplu11-1.fna.fbcdn.net/v/t39.2365-6/14858155_1136082199802015_362293724211838976_n.png?oh=c309fe47580aebb01a8b62038ddbf6ea&oe=5A68ECDD)

and all the entrys looks the same.

And you can put buttons on each entry, even the cover. However **BLiP** does't support it yet . 
You can use a **BLiP** **JsonDocument** to send to **Facebook** it's native json and you can customize it.

(Here is the documentation about list template https://developers.facebook.com/docs/messenger-platform/send-messages/template/list/)

The cover just appears on mobile devices, messenger desktop shows only the regular lists.

**Comment by andrebnassis** [comment]
All the suggestions were done! Thanks for the comments!
